import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import CustomCursor from "@/components/CustomCursor";

const peyda = localFont({
  src: [
    {
      path: "../fonts/PeydaWebFaNum-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/PeydaWebFaNum-Thin.woff2",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-peyda",
});
const eng = localFont({
  src: [
    {
      path: "../fonts/CreatoDisplay-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../fonts/CreatoDisplay-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/CreatoDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },

    {
      path: "../fonts/CreatoDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/CreatoDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/CreatoDisplay-Light.woff2",
      weight: "300",
      style: "normal",
    },

  ],
  variable: "--font-eng",
});
export const metadata: Metadata = {
  title: "Account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${peyda.variable} ${eng.variable}`} suppressHydrationWarning>
        <SmoothScroll /> {/* 👈 Lenis client logic here */}
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
